server:
 port: 8080
 servlet:
   context-path: /identity
spring:
 datasource:
   url: "jdbc:mysql://localhost:3306/identity_service_db"
   username: root
   password: 123456
   driver-class-name: com.mysql.cj.jdbc.Driver
 mail:
   host: smtp.gmail.com
   port: 587
   username: your-email@gmail.com
   password: your-app-password
   properties:
     mail:
       smtp:
         auth: true
         starttls:
           enable: true
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
       format_sql: true
       transaction:
         auto_close_session: true
   open-in-view: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace



jwt:
  signerKey: "ECmibn88gQej50jA9obcaWmzJc3+hgkY2xu57HYwN/0ggQ7zcpO3vUmk/8yAg2Sv"